project:
  type: website

website:
  title: "Tejomay's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tejomaygadgil/
      - icon: twitter
        href: https://twitter.com/tejomaygadgil/
format:
  html:
    theme: cosmo
    css: styles.css



