project:
  type: website

website:
  title: "Tejomay's blog"
  site-url: https://tejomaygadgil.github.io/
  navbar:
    right:
      - text: "About"
        file: about.qmd
      - icon: github
        href: https://github.com/tejomaygadgil/
format:
  html:
    theme: cosmo
    css: styles.css
    highlight-style: arrow 



