---
title: "Introduction to Aristotle's *Categories*"
author: "Tejomay Gadgil"
date: "2023-11-07"
categories: 
  - Philosophy
format:
  html:
    comments:
      utterances:
        repo: tejomaygadgil/tejomaygadgil.github.io
number-sections: true
---

Few essays in the history of philosophy are as important, less as inscrutable, and none as important for *being* inscrutable as Aristotle's *Categories*.

The central tension of this work between utterance (τὰ λεγόμενα) and beings (τὰ ὄντα) has divided readers for over twenty-five centuries as to what it is actually about. Is it language? Logic? Metaphysics? Something else entirely?

Introducing such an evasive text is therefore impossible: a full account of its meaning and history would not fit into the space of an introduction, while a few factual "hors d'oeuvres," no matter how well presented, would fail to introduce the actual *work* in question. Summary will never introduce us to the *Categories*. Instead our only option is to interpret it.

To interpret something means to put it in your own words. In interpretation the barrier between the work being interpreted and the work of interpretation begins to teeter. This softening the offset between ourselves and what we are trying to understand is what we call being "introduced." Interpretation is always difficult, not just because it is "hard," but because it is fundamentally *productive*.

This introduction, therefore, is nothing other than a plain English interpretation of the *Categories*, where "plain" hardly means easy or simple. Decisions have been made, and points have been rendered in order to practically engage the reader with the material ordering, as it always does, the words on the page.

## Things can have a common name for different reasons

Synonyms have a common name for the same reason: a cat and a bird are both "animals" because they are both living entities.

Homonyms have a common name for different reasons: a cello and a microscope are both "instruments," the former because it produces music, and the latter because it is a tool for science.

Paronyms share a common root: to preach and preacher, for instance.

## Beings can be predicates, and they can be properties

Utterances (τὰ λεγόμενα) can be interwoven in speech, or not: the former produces propositions such as "The man runs," the latter simple terms such as "man," and "runs." This will become relevant later.

Beings (τὰ ὄντα) can distinguished in two ways: as predicates, or as properties.

Predicates describe a subject (καθ' ὑποκειμένου λέγεται). Man, for instance, is the entity that characterizes a person, and tall is something that describes a redwood tree. Predicates are always generic.

Particular things are the opposite of a predicate. You cannot describe anything using a particular. Particulars cannot complete a sentence of the type "X is \_\_\_."

Consider your phone. It is a particular entity. *Your phone could never describe another entity*; rather it can only *be* described by generic predicates such as model number, color, size, shape, and so on.

Even the seeming counter-example "My favorite thing is this phone," is actually the [anastrophe](https://en.wikipedia.org/wiki/Anastrophe) of the proper statement "This phone is my favorite thing", where "favorite thing" is a predicate.

Properties belong to a subject (ἐν ὑποκειμένῳ ἐστιν). Examples include colors, height, length, location, and so on: you will never encounter "blue" or "tall" on its own, but only as an attribute of a pre-existing thing.

Substance (ἡ οὐσία) opposes property. And what is that, substance? Indeed, the rest of this work -- and the overall movement of philosophy itself -- will radically address this question. But for the time being, you can think of substance as *individuality*: that by which you can single out something particular as being something particular.

But what about the subject? If predicates describe a subject, and properties belong in a subject, shouldn't the subject oppose them instead of particulars and substance?

Not exactly, for the fact that predicates and properties can themselves be subjects! For the human that this man is *is itself* an animal, and for this man who wears a jacket that is green, that green *is itself* a color. Then a subject can either be a particular thing, or predicates describing that thing, properties belonging in that thing, or predicates describing those properties.

Draw it out: according to what we have discussed so far, everything we say about anything, *speech itself*, appears to spiral out of what we call particulars, and particularly what we call substance.

The two conditions by which we can distinguish beings, as predicates or as properties, in turn produce a table with four categories:

|                                       | **Not a predicate**<br>**(Particular things)** | **Predicate** |
|------------------------|------------------------------|------------------|
| **Not a property**<br>**(Substance)** | This man                                       | Man           |
| **Property**                          | This knowledge                                 | Knowledge     |

Here everything interlaces in a complex crossing:

-   **Property predicates** are generic descriptors of properties: knowledge, color, shape, and so on.
-   **Substantial predicates** are generic descriptors of particulars: human, horse, cars, and more general labels like animal, vehicle, and so on.
-   **Property particulars** are specific details about particular things: the flakiness of a pastry, the specific way someone walks, the sound your car makes when it turns on.
-   Then, finally, **substantial particulars**: the individual things -- that is, everything surrounding you at all times -- in the world that can be described with predicates and that possess properties (that in turn can also be described). But they never themselves describe or belong to anything else.

From this a certain *ordering* about the nature of the world has been implanted: there is a sense in which ideas, concepts, descriptions, generic terms, and possibly language itself *come second* to the particular things we encounter around us.

## Genera also describe things

In the language of Aristotle, these predicates of predicates are called "genera," while the predicates underneath describing actual things are called "species."

Genera apply downward to the particulars. So if a man is a human, and humans are animals, then that man is also an animal.

Species within a genus are distinguished by "differentiae." Species of animal can be distinguished by being footed, winged, and so on.

Differentiae of one genus have no bearing toward an unrelated genus: knowledge, for instance, cannot be distinguished by footed, winged, and so on.

But differentiae of a genus can apply downward: the bird genus, underneath animal, itself contains species that may be distinguished as being footed (flightless), winged (flighted), and so on. This does not always hold (human is not distinguished by being footed or winged), but it is possible.

## Every word refers to one of ten things

Every uncombined utterance (word) ultimately means one of the following:

| English   | Greek   | Section        |
|-----------|---------|----------------|
| Substance | οὐσία   | @sec-substance |
| Quantity  | πόσος   | @sec-quantity  |
| Quality   | ποιός   | @sec-quality   |
| Relation  | πρός τι | @sec-relation  |
| Place     | ποῦ     | Not discussed  |
| Time      | ποτὲ    | Not discussed  |
| Posture   | κεῖσθαι | @sec-relation  |
| State     | ἔχειν   | Not discussed  |
| Action    | ποιεῖν  | Not discussed  |
| Affection | πάσχειν | @sec-quality   |

**Insofar as all speech consists of words, these ten things, it seems, constitute the meaning of speech in general.**

If words are signs referring to things ("cat" stands in for the idea of a type of fuzzy four legged creature, and "my cat" is shorthand for the actual fuzzy animal that lives with me), then these ten concepts, it seems, must be the ultimately what all words signify. Perhaps they constitute the layout of the "ground floor" of what we must constantly be referring to when we go about talking in our everyday lives.

Here also Aristotle also notes here that only combined utterances, statements, strictly speaking, be true or false.

The remainder of the text will discuss six of these categories in detail: Substance, Quantity, Quality and Affection, and Relation and Posture.

## Substance {#sec-substance}

There are two kinds of substance (ἡ οὐσία), first and second.

First substance refers to *actual things*: these are the particular objects we discussed in the first classification.

First substance is truly the *first* utterance in that everything else we speak of seems takes root in actual things. If first substance did not exist, the rest -- species, genera, differentiae, and properties -- simply could not exist. Therefore of utterances it is the first.

Secondary substance refers to substantial predicates: to the species, genera, and differentiae that describe *what actual things are*.

Only second substance describes actual things synonymously. So if this man is a man, then the definition of man, animal, applies to him. On the other hand, this man having skin of a certain shade (a property) does not proceed to define him as a color: it is homonymous.

Species is more substantial than genre. For one, it is "nearer" to substance in being a more natural substitute: it is more sensible to call this man a man than it is to call him an animal. Species also behaves more like substance in that it describe less things than genre.

Second substances, despite being predicates, are truly substances:

For even though they are descriptions, species and genre alone pertain to and clarify *what first substances are*. For you can measure whatever you like about a man -- his height, his knowledge, age, posture, and so on -- none of these properties will tell you *what he is*: a man.

Species and genre can also be described like first substance: for if this man is said to walk on two legs and possess knowledge, then the same can be said of man and animal. Species and genre are never also properties belonging to a subject. Properties, as established above, name the subject homonymously, but secondary substances do so synonymously. For if this pen is a pen, that also makes it an artificial device.

Let us define first and secondary substance a bit more carefully.

**First substance is what all speech is about.** It is what all utterance, no matter how, what where, or why it is being said, refers to.

This is why Aristotle defines first substance as τόδε τι, something with the basic character of being *pointed out*. All speech fundamentally points to substance, and substance cannot be understood in any other capacity than this basic ability to be referred to and remarked.

Accordingly, second substance clarifies substance by its *kind*. By pointing to an actual thing as a human or a dog,

## Quantity {#sec-quantity}

## Quality {#sec-quality}

## Relation {#sec-relation}